# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crockerometer', '0002_auto_20160927_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomWoojit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
