# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crockerometer', '0003_randomwoojit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RandomWoojit',
            new_name='Woojit',
        ),
    ]
