# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crockerometer', '0004_auto_20160929_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
