# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 09:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crockerometer', '0005_vote_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=10, max_digits=11, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Woojit',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='users',
            field=models.ManyToManyField(through='crockerometer.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crockerometer.Rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crockerometer.Metric'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
