# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crockerometer', '0006_auto_20161005_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=11, null=True),
        ),
    ]
